proxy: &proxy
  default: !include lang-proxy.yaml

deu-mob-ban:
  lang: 'deu'
  proxy:
    <<: *proxy
  device:
    type: mobile
    name:
      - 'Nexus 5'
      - 'iPad Mini'
  links:
    ban:
      - 'https://horny-honey.online/landers/test_clicker_notjump/test_clicker_notjump/index.html'
  maxclick:
    interval_h: 1
    count: 1000
